---
title: "《星期五不上班》"
description: "Overtime: Why We Need A Shorter Working Week"
author: "Awesome Yi"
date: "2026-08-28"
categories: [书摘]
---

# Book Information

Overtime: Why We Need A Shorter Working Week

Authors: Will Stronge and Kyle Lewis

ISBN: 9781788738682

# 导言：一场与资本主义一样古老的斗争

能够放松、与所爱的人共度时光、从事自主活动并从老板那里获得自由，都是人之为人的基本要素。毕竟，时间就是生命。

英国Universal Credit

工作不再能减轻贫困，为公民提供自由和安全。工作的特点是无保障的合同、为公民提供自由和安全。在21世纪的英国，工作的特点是无保障的合同、惩罚性的监视和无法满足基本生活需求的工资。

自罗斯福总统的新政将工时上限纳入美国立法以来已经过去了80多年；自英国将每周工作40小时确定为新的标准以来，也已经过去了70多年。

我们必须认识到，仅凭就业还不能被看作是为个人提供健康和经济保证的充分条件。只有当工作能够提供社会条件，使全人类能够相互合作、合理安排时间、获得尊严感，并获得必要的物质手段以便生活在安全且有保障的环境中时，工作才能被认为是帮助人类繁荣发展的充分条件。

将自由置于工作之上，将生活置于工作之上。

# 生活于工作至上的社会中

在资本主义内部，时间也是金钱。人们获得的工资取决于他们付出时间的多少，而在这些有偿时间内，雇主希望他们尽可能多的产出。从这个角度看，时间是盈利企业的另一种生产成本。

为了享受我们为之辛劳的生活，我们还需要时间，而我们的老板想要抓住的正是我们的生活时间。

事实上，在人类历史的漫长岁月里，实际上是数10万年--每周安排我们的食物和其他生活事项大约需要15~17个小时，我们剩下的时间都花在了其他追求上。

从根本上说，就业与个人自由相对立，它意味着在一定时间内将自己出租给某个人或某个公司。

这些疾病的主要原因是什么？工作压力或者更准确的说是:截止日期紧迫，工作量太大或压力太大。

# 未开发的潜力：节省劳动力的技术与人类繁荣

这些疾病的主要原因是什么？问号。工作压力或者更准确的说是截止日期紧迫，工作量太大或压力太大。

对于凯恩斯来说，这一趋势非常明显，只要经济持续增长，生产所需的人力劳动时间将越来越少，每周工作时间将继续缩短，也许到2030年会缩短到15个小时左右。

但为什么我们的每周工作时间没有随着经济增长而减少，而这恰好体现了分配的重要性。而凯恩斯的乐观的缺陷就在于此。事实上，在19世纪末和20世纪初的几十年里，生产力提高。与工时缩短之间的相关性，并不是经济或自然法则的产物，而是工会和公众人物为缩短工时发起的政治活动日益壮大的结果。

那些一生都在执行简单且重复的操作的人，根本没有机会发挥他的理解力。

资本主义社会在技术和科学领域的进步不过是在压榨汗水方面的进步。

巴塔耶问道，所有这些积累的目的是什么?什么时候才是享受的时候?什么时候我们的日常活动本身才是目的，比如游戏、性、探索，享受音乐、电影和其他艺术?这些“至高无上”的活动(相对于不停工作的奴性)常常被鄙视为“精英主义”，轻浮的奢侈品，或者干脆就是“浪费时间”。在巴塔耶看来，这是对事实的极端曲解:现代的重复性工作毫无意义，除非我们可以在此基础上超越持续的折磨。

从本质上来说，凯恩斯常识中的一些元素值得保留:从技术进步中获得的生产力提升，不仅能够而且应该带来更短的工作周。除了极大地减少贫困和匮乏(这不是个小数目!)，这还让我们有机会思考什么是最重要的，并为之采取行动，让我们的思维不仅仅局限于“生产”，并最终成为一个更加充实的人，拥有更广阔的视野，而不仅仅是维持生计。但我们应该从历史中吸取的教训是，这样理想的局面不会随着生产技术的进步自然而然地出现，而必须通过在社会各个层面上要求、争取和运动来实现。

# 属于女性的时间与更短的工作周

换句话说，尽管妇女平权运动确实取得了成就，但女性在经济中承担的主要角色仍然是照护、清洁和情绪劳动。

研究发现，高风险工作中的劳动力中有77%是女性，而在那些从事高风险工作且只获得贫困线工资的劳动者中，女性比例高达98%。

21世纪初的自由派政治家试图发起倡议，推广“工作-生活” 平衡(“work-life”balance)，以此来解决女性显著的时间负担。这个术语的使用和流行都起源于1960 年代的妇女解放运动，但其后继者新自由主义的重新诠释却偏离了集体解放女性的愿景，而是转向雇主和工人之间更加个体化的关系。

# 争取缩短工作周的斗争

1975年10月24日，冰岛，Long Friday.

德国，Kurzarbeit

在多重危机面前工会的诉求要从保卫工作转向维护“工人从劳动中解放、增加闲暇时间”的自由。

历史上最大幅度的工作时间缩减并不是发生在经济繁荣时期，而是在两次灾难性的世界大战之后。认为我们只有到了经济复苏的时候才能提高生活水平，获得更多的自由时间，这是一个我们经常落入的思维陷阱。我们必须质疑而非接受这种思维方式，我们的经济活动带来了巨大的财富，但财富的分配却糟糕的难以置信。12%的家庭拥有着约50%的私人财富（英国）。
