project:
  type: website

execute:
  freeze: auto

website:
  description: "A blog of Awesome Yi"
  site-url: https://awesomeyi-blog.share.connect.posit.cloud
  title: "Awesome Yi"
  image: profile.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Python"
        href: python-series.qmd
      - text: "R"
        href: r-programming.qmd 
      - text: "AI"
        href: ai.qmd
      - text: "Buddism"
        href: buddism.qmd
      - text: "About Me"
        href: about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/mickeyang/
format:
  html:
    theme:
      - simplex
    css: styles.css



