---
title: "Week Four Day Two (W4D2)"
description: "Shrink Parquet Column and Compress Parquet Dataset"
author: "Awesome Yi"
date: "2026-06-14"
categories: [Week4]
---

> There are two techniques enabling column shrink and dataset compression, including `Dictionary Encoding` and `Run-Length Encoding`.

# Dictionary Encoding

Apply highly intelligent encodings to turn repetitive text into mathematical shorthand, by building a small internal dictionary matrix for repetitive values. This technique works best when a column has few unique values (low-cardinality columns), and values are repeated a lot.

## Example

Think about a column containing fruit names, such as ["apple", "banana", "apple", "apple", "banana"]. The Dictionary Encoding technique would map apple to 1 and banana to 2. Therefore, the column would be "transformed" to [1, 2, 1, 1, 2].

```
{
    "apple" : 1,
    "banana" : 2
}
```

## Benefits

1. Storing small integers (0, 1, …) is much cheaper than storing full strings.
2. Especially powerful for low-cardinality columns (few unique values).
3. Encoded integers compress better with algorithms like RLE (Run-Length Encoding).
4. Operations like filtering (`WHERE fruit = 'apple'`) can be done on the encoded integers.
5. Less data to scan = faster reads.

# Run-Length Encoding (RLE)

Instead of writing [0, 0, 0, 0, 0], RLE compresses the list into a simple counter expression: "Five zeros" (5 * 0). This requires analysts sorting specific columns **BEFORE** exporting data to a parquet file.


::: {.callout-tip}
Sorting your data by high-repetition columns (like country, status, or date) right before writing it to a Parquet file will drastically shrink the file size and accelerate read performance.

You can typically only choose one or two primary columns to sort your data by before writing. **Always pick the columns that are highly repetitive (for compression) and frequently used in your SQL WHERE clauses (for search speed)**.
:::
