---
title: "Week Three Day Four (W3D4)"
description: "Thread-Safe Queue `queue.Queue`"
author: "Awesome Yi"
date: "2026-06-08"
categories: [Week3]
---

# Why necessary

locks keep our data safe but introduce a major downside: they slow things down by forcing threads into a single-file line. If your threads spend all their time waiting in line to touch a shared asset, your concurrency benefits vanish.

---

# How: Producer-Consumer Architecture (经典并发设计模式)

Decoupling a pipeine by using the producer-queue-consumer design，从而提高模块的独立性。可以通过调整producer和consumer的数量来平衡两者之间处理事务的速度差。

## Producers (P) - `queue.put()`

Their sole job is to harvest data as fast as possible from a source (like scraping endpoints) and drop it into a holding area.

## Consumers (C) - `queue.get()`

Their sole job is to grab data out of that holding area, transform it, and load it into its final destination.

The `Consumer` function uses a `while` loop, which is constantly waiting for new items and should be terminated when no data can `get` from a `queue`, then use `break` to jump out the loop. Besides, when all items are consumed, we will have to tell the queue the task is done by calling `queue.task_done()`.

For every item retrieved with `queue.get()`, we must call `queue.task_done()` when we are finished processing it. This tells the queue that the task is complete.

The holding area in the middle is a **Queue**.

## Queue (Q)

- A queue is a data structure that follows a "First-In, First-Out" (FIFO) principle. The first item you add is the first one to be removed.

- When using a `Queue`, the module has internal locking mechanisms built right into its core, hence no need to use `with data_lock`.

### Methods

- q.put(), put to the BACK of a queue

- q.get(), get from the FRONT of a queue

- q.task_done()
