---
title: "English Vocabulary"
description: "Detailed definitions"
author: "Awesome Yi"
date: "2026-07-24"
categories: [vocabulary]
--- 

Click on below links for more details.

> Note: this list is generated by the `compile-vocabulary-list.R` program. **DO NOT execute** this program from the ROOT folder.

- [TANTRUMS](../../ai-english/english-tantrums.md)
- [SLACKER](../../ai-english/english-slacker.md)
- [ULTIMATUM](../../ai-english/english-ultimatum.md)
- [MALVERTISE](../../ai-english/english-malvertise.md)
- [INFOSTEALER](../../ai-english/english-infostealer.md)
- [RENTINGATITLE](../../ai-english/english-rentingATitle.md)
- [COLDCALL](../../ai-english/english-coldcall.md)
- [GENUINE](../../ai-english/english-genuine-transformed.md)
- [CRYPTIC](../../ai-english/english-cryptic-transformed.md)
- [CANONICAL](../../ai-english/english-canonical.md)
- [SPOOFING](../../ai-english/english-spoofing.md)
- [ENDIANNESS](../../ai-english/english-endianness.md)
- [EPHEMERAL](../../ai-english/english-ephemeral.md)
- [SPRAWL](../../ai-english/english-sprawl.md)
- [ERGONOMICS](../../ai-english/english-ergonomics.md)
- [HUNCH](../../ai-english/english-hunch.md)
- [OCTET](../../ai-english/english-octet.md)
- [IDIOMATIC](../../ai-english/english-idiomatic.md)
- [OBSCURE](../../ai-english/english-obscure.md)
- [INTERPOLATION](../../ai-english/english-interpolation.md)
- [EXTRAPOLATION](../../ai-english/english-extrapolation.md)
