---
title: "Recent vocabulary"
author: "Awesome Yi"
date: "2026-04-18"
categories: [vocabulary]
---

Some English and Chinese vocabulary

# 2026-04-18

- 绥(sui)阳

- caveat (warning)

- snazzy (stylish)

- tug of war (拔河)

- fraudster (诈骗犯）

- spoof (a funny and silly piece of writing, music, theatre, etc. that copies the style of an original work)

- number spoofing (冒充电话号码）

- hoax （a plan to deceive a large group of people; a trick）

- malicious (intended to harm or upset other people)	

# 2026-05-15

- linchpin = lynchpin (a person or thing vital to an enterprise or organization, 核心人物和thing)

- idempotent （无意义的重复）

- finicky (难取悦， 挑剔的人)

- demarcate from/by (separate, 分开，隔离开)

# 2026-05-20

- 偈子 （ji zi, 佛经中的唱颂词，也叫偈颂、偈诗，源自梵语Gatha。通常以四句为一偈。它既是仪式开场的偈诗，也是禅宗高僧用以直指人心的顿悟载体。）

- 声色犬马 （歌舞女色，玩狗骑马。形容骄奢淫逸的生活。常用来批评沉迷低级趣味、荒废正事的行为。）

- 耆那教 （qi na)， 以五戒“不杀生、不妄语、不偷盗、不淫欲、不执取”为核心，强调通过苦行清除业障，使灵魂回归清净。

- 受限制盈余 （指公司账面利润中被强制保留、无法自由分配给股东的那部分，通常需再投入设备更新或满足监管要求，因此不能算作真正可支配的赚钱能力。巴菲特用它区分“赚钱机器”和“烧钱机器”。

- 砵酒 （port wine, 葡萄牙北部杜罗河谷产的**加强型甜**红葡萄酒，发酵时加白兰地停糖，入口焦糖巧克力味，配茶或餐后皆宜。）

# 2026-05-24

- bilerplate (text that can be copied and used in legal documents or in computer programs, with only very small changes, （在法律文件或者计算机程序中略微修改即可使用的）文件样板，文件范例)

- `DRY` programming principle (**D**o not **R**epeat **Y**ourself)

- 窠臼 （Ke Jiu, 比喻陈旧、一成不变的规格模式)

- 鹣鲽情深 (Jian Die Qing Shen，比喻人与人之间感情深厚，尤指夫妻之间的恩爱和相濡以沫)

- 本质化思维 (把事物某个属性当成绝对本质，并用它去解释一切现象，它省力、能预测，却也让人执着于“学生就该在教室”这类标签，把环境变化看成反常，从而减低心理承受力。)

# 2026-05-27

- iron out (resolve problems, remove)

- quirk (an unusual habit or part of someone's personality, or something that is strage and unexpected)

- precipice (a very steep side of a cliff or a mountain, a dangerous situation that could lead to harm or failure)

- avid (extremely eager or interested)

- clumsy (a clumsy person often has accidents because they do not behave in a careful, controlled way)

- prudent (careful and avoiding risks)

# 2026-06-02

- attestation (evidence or proof of something; the action of formally witnessing or certifying something)

- payload (in computing and telecommunications, the payload is the part of the data that carries the intended message or content. Headers and metadata are considered overhead because they provide routing and control information, not the actual data)s

- deep breadcrumb trail (a deep breadcrumb trail is a website navigation feature that shows a long or highly specific hierarchical path from the homepage to a very specific subpage. It helps orient users when they "teleport" directly onto a narrow, specific page via a search engine)

- breadcrumb (a "breadcrumb" primarily refers to a small piece of dried bread. However, the term is frequently used metaphorically in digital navigation and psychology)

- telemetry (automated process of collecting measurements or data at remote or inaccessible points and transmitting them to a central location for monitoring, analysis, and action)

# 2026-06-04

- bulletproof (designed to resist the penetration of bullets, e.g., a bulletproof vest 防弹背心)

- blip (a temporary change that does not have any special meaning; a small spot of light, sometimes with a short, sharp sound, that appears on a computer screen)

- ironclad (very certain and unlikely to be changed, impossible to contradict, weaken, or change)

- pickling tax (A Pickling Tax is a historical term referring to the taxation of pickled and preserved foods)

# 2026-06-11

- obliterate （destroy utterly; wipe out）

- interleave (mix (digital signals) by alternating between them)

- jumble (mix up in a confused or untidy way)

- garble (reproduce (a message, sound, or transmission) in a confused and distorted way)

- throttle (press someone's throat or to prevent something from succeeding)

# 2026-06-20

- reap (cut or gather a crop or harvest)

- ephemeral (=transient, lasting for a very short time)

- prose (talk tediously)

- stumble (to hit your foot on something when you are walking or running so that you fall or almost fall)

# 2026-07-02

- [extrapolation](../../ai-english/english-extrapolation.md)

- [interpolation](../../ai-english/english-interpolation.md)

- [obscure](../../ai-english/english-obscure.md)

- [idiomatic](../../ai-english/english-idiomatic.md)

- [genuine](../../ai-english/english-Genuine.md)

