---
title: "Week Two Day Two (W2D2)"
description: "Using `Pydantic` to validate and parse data respecting desired data schema."
author: "Awesome Yi"
date: "2026-06-01"
categories: [Week2]
---

> Pydantic is not only a validation library, but also a parsing library.

---

# What is Pydantic BaseModel

在Pydantic库中，BaseModel是所有数据模型的基类。在使用时，需要从Pydantic库中引用。在Pydantic V2中，推荐使用`@field_validator`。

By default, 在使用BaseModel构建新的class（类）的时候，class中的字段名需要和payload数据中的字段名一致。但也可以在定义class的过程中使用alias去映射payload中不同得字段名称。另外，在class中建议使用更清晰的命名方式，而payload中可以使用稍微简洁的命名。

```
from pydantic import BaseModel, Field

class UserModel(BaseModel):
    user_id : int = Field(..., alias = "id")  # using alias would PASS both "user_id" and "id" columns
    age : int
    MIN_AGE = 18

    model_config = {"extra": "allow"}  # allow more columns/fields in payload but NOT in the class definition, other options include "forbid" and "ignore"

    
    @field_validator("age")  # field validation
    def check_age(cls, v):  # cls here refers to the UserModel class itself, like self
        if v < 0:
            raise ValueError("Age cannot be a negative value.")
        if v < cls.MIN_AGE:
            raise ValueError(f"Age must be at least {cls.MIN_AGE}")

        return v

user = UserModel(user_id = "1", age = 20)  # character "1" will be automatically converted to integer 1
```

## Functions

```
user.model_dump()  # dump to a dictionary
user.model_dump_json()  # dump to a JSON
user.model_copy()
user.model_fields()
```

# Example

```
from datetime import datetime
from pydantic import BaseModel, ValidationError

# 1. Define the Firewall Schema
class UserModel(BaseModel):
    user_id: int
    username: str
    signup_date: datetime  # Pydantic will automatically parse ISO strings into datetime objects
    is_active: bool

# 2. Simulate raw, messy data from an API
raw_api_payload = {
    "user_id": "1001",                 # Str instead of Int (Pydantic will coerce this!)
    "username": "data_wizard",
    "signup_date": "2026-06-01T12:00:00", # String date (Pydantic will parse this!)
    "is_active": "True"               # Str instead of Bool (Pydantic will coerce this!)
}

# 3. Pass data through the firewall
try:
    user = UserModel(**raw_api_payload)  # `**` is used to UNPACK payload dictionary
    print(f"Successfully parsed user: {user.user_id}")
    print(type(user.signup_date)) # Output: <class 'datetime.datetime'>
except ValidationError as e:
    print(f"Schema violation! Details: {e.json()}")
```

# Lab session

```
from typing import Literal
from pydantic import BaseModel, ValidationError

# Testing data
mock_orders = [
    {"order_id": 101, "price": "29.99", "item_name": "Logitech Mouse", "status": "PENDING"},
    {"order_id": 102, "price": 1099.00, "item_name": "4K Monitor", "status": "INVALID_STATUS"},
    {"order_id": "one-hundred-three", "price": 5.50, "item_name": "HDMI Cable", "status": "SHIPPED"}
]

# 1. Define the Firewall Schema, THIS IS THE CORE CONFIG
class OrderModel(BaseModel):
    order_id: int
    price: float
    item_name: str
    status: Literal["PENDING", "SHIPPED", "DELIVERED"]


# 2. Pass data through the firewall
for o in mock_orders:
    print(o)
    try:
        order = OrderModel(**o)    
        print(f"Order {order.order_id} is clean.")
    except ValidationError as e:
        # Loop through the structured errors Pydantic provides
        for error in e.errors():
            field = " -> ".join(str(loc) for loc in error["loc"])
            error_msg = error["msg"]
            print(f"   • Field [{field}]: {error_msg}")
```

# Furthermove

在传入payload时，`**`的作用是`字典解包`(dictionary unpacking)，它会把一个**字典**(dict)拆解成关键字参数(keyword arguments)。这是常用的初始化一个Pydantic class方法，同时还有其它两种方式可以初始化，如下:

- UserModel(**payload) 常用的方式，适用于dict和JSON

- UserModel(id=1, name="Alice")

- UserModel.model_validate(payload) 这是最Pydantic v2 最推荐的

## 推荐使用`model_validate(payload)`
在Pydantic V2中，能用`UserModel.model_validate(payload)`的，就不要使用`UserModel(**payload)`。使用`model_validate(payload)`的好处包括，但不限于:

- 原生支持alias

- 支持严格模式 (不自动将字符"123"转为123, 需要配置`model_config = ConfigDict(strict=True)`)

- 错误信息更清晰

- 未来兼容性更好

- 可以兼容payload中多余的字段，比如使用`extra="ignore"`
